template_shop/admin_panel/app/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash

from template_shop.admin_panel.app import db, login_manager
from template_shop.admin_panel.app.forms.auth import LoginForm
from template_shop.infrastructure.database.models import AdminUser

auth_bp = Blueprint("auth_bp", __name__, template_folder="templates", static_folder="static")


@auth_bp.route("/admin/login", methods=["GET", "POST"])
@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    """
    Log-in page for registered users.
    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """

    if current_user.is_authenticated:
        return redirect("/")

    login_user_form = LoginForm()
    if login_user_form.validate_on_submit():
        email = login_user_form.email.data
        password = login_user_form.password.data

        user = db.session.query(AdminUser).filter_by(email=email).first()
        redirect_url = "/"

        if (not user) or (not check_password_hash(user.password, password)):
            flash("Please check your login details and try again.")
            return redirect(request.url)

        login_user(user)
        next_page = request.args.get("next")
        if next_page:
            return redirect(next_page)
        else:
            return redirect(redirect_url)

    return render_template(
        "login.html",
        login_user_form=login_user_form,
    )


@auth_bp.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        existing_user = db.session.query(AdminUser).filter_by(email=request.form.get("email")).first()
        if existing_user is None:
            user = AdminUser(email=request.form.get("email"))
            user.set_password(request.form.get("password"))
            db.session.add(user)
            db.session.commit()  # Create new user
            login_user(user)  # Log in as newly created user
            return redirect("/")
        flash("This email is already used")
    if current_user.is_authenticated:
        return redirect(url_for("dashboard_bp.home"))

    return render_template(
        "signup.html",
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""

    if user_id is not None:
        try:
            user = db.session.query(AdminUser).get(user_id)
        except:
            user = None
        return user
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash("Log in to view this page")
    return redirect(url_for("auth_bp.login"))


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth_bp.login"))

template_shop/admin_panel/app/views/settings.py
from template_shop.admin_panel.app.views import MyBaseModelView


class SettingsModelView(MyBaseModelView):
    column_labels = {
        "certificate": "Лимит в складчине по сертификатам",
        "declaration": "Лимит в складчине по декларациям",
        "declaration_gost": "Лимит в складчине по декларациям ГОСТ",
        "letter": "Лимит в складчине по отказным",
        "sgr": "Лимит в складчине по СГР",
        "sgr_declaration": "Лимит в складчине по СГР + Декларации",
        "bills_checker_enabled": "Проверка оплат включена",
        "bills_checker_days": "За сколько дней проверять оплату",
        "referral_notify_enabled": "Отправка уведомлений о рефералах включена",
    }

    column_exclude_list = "description"

template_shop/admin_panel/app/templates/myadmin3/change_avatar.html
{% extends 'myadmin3/my_master.html' %}
{% block head_css %}
    {{ super() }}
    <link rel="stylesheet" href="https://cdn.staticfile.org/jquery-jcrop/0.9.12/css/jquery.Jcrop.min.css">
{% endblock head_css %}

{% block body %}
    {{ super() }}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Change Avatar</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ admin_view.admin.url }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ url_for('profile.index') }}">User Profile</a></li>
                        <li class="breadcrumb-item active">Change Avatar</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <div class="container">
        <section class="section team-section">
            <div class="row">
                <div class="col-md-6">
                    <form method="POST" action="{{ url_for('profile.upload_avatar') }}" enctype="multipart/form-data">
                        {{ upload_form.csrf_token }}
                        <div class="md-form mb-3">
                            {{ upload_form.image }}
                        </div>
                        <div class="form-group">
                            {{ upload_form.submit }}
                        </div>
                    </form>

                    <small class="text-danger">
                        Your file's size must be less than 3 MB, the allowed formats are png and jpg.
                    </small>
                </div>

                <div class="col-md-6">
                    {{ avatars.crop_box('auth.get_avatar', current_user.avatar_raw) }}
                    {{ avatars.preview_box('auth.get_avatar', current_user.avatar_raw) }}
                    <form method="POST" action="{{ url_for('profile.crop_avatar') }}">
                        {{ crop_form.csrf_token }}
                        {{ crop_form.x }}
                        {{ crop_form.y }}
                        {{ crop_form.w }}
                        {{ crop_form.h }}
                        <div class="form-group mt-1">
                            {{ crop_form.submit }}
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

{% block tail_js %}
    {{ super() }}
    <script src="https://cdn.staticfile.org/jquery-jcrop/0.9.12/js/jquery.Jcrop.min.js"></script>
    {{ avatars.init_jcrop() }}
{% endblock tail_js %}

template_shop/admin_panel/app/templates/myadmin3/ckeditor.html
{% extends 'flask-admin/model/create.html' %}

{% block tail %}
    {{ super() }}
    {{ ckeditor.load() }}
{% endblock %}

template_shop/admin_panel/app/templates/myadmin3/my_index.html
{% extends 'myadmin3/my_master.html' %}
{% import 'flask-admin/static.html' as adminlte_static with context %}
{% block body %}
    {{ super() }}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Dashboard</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ admin_view.admin.url }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                    <div class="col-auto ms-auto d-print-none">
                        <div class='row'>
                            <div class='col-lg-4'>
                                <label class='form-label'>Дата от:</label>
                                <input class='form-control' type='date' name='date' id='datefrom'
                                       value="{{ dates[0] }}"/>
                            </div>
                            <div class='col-lg-4'>
                                <label class='form-label'>Дата до:</label>
                                <input class='form-control' type='date' name='date' id='dateto'
                                       value="{{ dates[-1] }}"/>
                            </div>
                            <div class='col-lg-4' style='align-self: flex-end;'>
                                <button type='button' class='btn btn-primary' id='changeDateButton'>Применить</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- ./col -->
                <div class="col-lg-4 col-6">
                    <!-- small box -->
                    <div class="small-box bg-success">
                        <div class="inner">
                            <h3 id="registered_users">{{ data.registered_users | sum }}</h3>
                            <p>Зарегистрировано пользователей</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-users"></i>
                        </div>
                        <a href="{{ url_for('users.index_view') }}" class="small-box-footer">Подробнее <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-warning">
                        <div class="inner">
                            <h3 id="co_buys_created">{{ data.products_purchased | sum }}</h3>
                            <p>Куплено товаров</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-cloud"></i>
                        </div>
                        <a href="{{ url_for('products.index_view') }}" class="small-box-footer">Подробнее <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
                <div class="col-lg-4 col-6">
                    <div class="small-box bg-danger">
                        <div class="inner">
                            <h3 id="orders_created">{{ data.orders_created | sum }}</h3>
                            <p>Создано заказов</p>
                        </div>
                        <div class="icon">
                            <i class="fas fa-shopping-cart"></i>
                        </div>
                        <a href="{{ url_for('orders.index_view') }}" class="small-box-footer">Подробнее <i
                                class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="col">
        <canvas id="stat_chart" data-dates="{{ data.dates }}" data-registered_users="{{ data.registered_users }}"
                data-orders_created="{{ data.orders_created }}" data-products_purchased="{{ data.products_purchased }}"
                data-payments_paid="{{ data.payments_paid }}"></canvas>
    </div>
    <div class="table-responsive">
        <table id="table_stats" class="table card-table table-vcenter text-nowrap datatable">
            <thead>
            <tr>
                <th class="w-1">Дата</th>
                <th>Новых пользователей</th>
                <th>Новых заказов</th>
                <th>Куплено товаров</th>
                <th>Оплачено счетов</th>
            </tr>
            </thead>
            <tbody>
            {% for date, row in table_columns %}
                <tr>
                    <td>{{ date }}</td>
                    {% for column in row %}
                        <td>{{ column }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            <tr>
                <td>Всего:</td>
                {% for column in data.rows_sums %}
                    <td>{{ column }}</td>
                {% endfor %}
            </tr>
            </tbody>
        </table>
    </div>
{% endblock body %}

{% block tail_js %}
    {{ super() }}
    <script>
        function tableToCSV() {
            var csv_data = [];
            var rows = document.getElementsByTagName('tr');
            for (var i = 0; i < rows.length; i++) {
                var cols = rows[i].querySelectorAll('td,th');
                var csvrow = [];
                for (var j = 0; j < cols.length; j++) {
                    csvrow.push(cols[j].innerText);
                }
                csv_data.push(csvrow.join(","));
            }
            csv_data = csv_data.join('\n');
            downloadCSVFile(csv_data);
        }
    </script>
    <script src="{{ adminlte_static.url('dist/js/charts.js') }}"></script>
{% endblock tail_js %}

template_shop/admin_panel/app/templates/myadmin3/my_master.html
{% extends 'flask-admin/base.html' %}

{% block nav_control %}
    <ul class="navbar-nav">
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{ admin_view.admin.url }}" class="nav-link">Home</a>
        </li>
    </ul>
{% endblock %}

{% block user_panel %}
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
            <a class="d-block" href="{{ url_for('auth_bp.logout') }}">
                {% if current_user.email %}
                    {{ current_user.email }}
                {% endif %}
            </a>
        </div>
    </div>
{% endblock user_panel %}

{% block model_menu_bar %}
{% endblock %}

template_shop/admin_panel/app/templates/myadmin3/settings.html
{% extends 'myadmin3/my_master.html' %}

{% block body %}
    {{ super() }}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Settings</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ admin_view.admin.url }}">Home</a></li>
                        <li class="breadcrumb-item active">Settings</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <section class="section team-section">
            <div class="row">
                <div class="col-md-8 mb-4">
                    <div class="card">

                        <form class="card-body" method="POST" action="{{ url_for('settings.index') }}">
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <div class="md-form form-sm mb-0">
                                        <label for="username">Binance API</label>
                                        <input type="text" name="username" class="form-control form-control-sm"
                                               id="username" value="{{ current_user.username }}">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="md-form form-sm mb-0">
                                        <label for="email">Webmoney API</label>
                                        <input type="text" name="email" class="form-control form-control-sm" id="email"
                                               value="{{ current_user.email }}">
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

template_shop/admin_panel/app/templates/myadmin3/user_profile.html
{% extends 'myadmin3/my_master.html' %}

{% block body %}
    {{ super() }}
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">User Profile</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ admin_view.admin.url }}">Home</a></li>
                        <li class="breadcrumb-item active">User Profile</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>

    <div class="container">
        <!-- Section: Team v.1 -->
        <section class="section team-section">
            <!-- Grid row -->
            <div class="row">
                <!-- Grid column -->
                <div class="col-md-8 mb-4">
                    <!-- Card -->
                    <div class="card">
                        <!-- Card Data -->
                        <div class="card-header text-center">
                            <h3 class="mb-0 font-weight-normal">Edit User Profile</h3>
                        </div>
                        <!-- Card Data -->

                        <!-- Card content -->
                        <form class="card-body" method="POST" action="{{ url_for('profile.index') }}">
                            <!-- Grid row -->
                            <div class="row mb-3">
                                <!-- Grid column -->
                                <div class="col-md-6">
                                    <div class="md-form form-sm mb-0">
                                        <label for="username">Username</label>
                                        <input type="text" name="username" class="form-control form-control-sm"
                                               id="username" value="{{ current_user.username }}" disabled>
                                    </div>
                                </div>
                                <!-- Grid column -->

                                <!-- Grid column -->
                                <div class="col-md-6">
                                    <div class="md-form form-sm mb-0">
                                        <label for="email">Email Address</label>
                                        <input type="email" name="email" class="form-control form-control-sm" id="email"
                                               value="{{ current_user.email }}" disabled>
                                    </div>
                                </div>
                                <!-- Grid column -->
                            </div>
                            <!-- Grid row -->

                            <!-- Grid row -->
                            <div class="row mb-3">
                                <!-- Grid column -->
                                <div class="col-md-6">
                                    <div class="md-form form-sm mb-0">
                                        <label for="first_name">First Name</label>
                                        <input type="text" name="first_name" class="form-control form-control-sm"
                                               id="first_name" value="{{ current_user.first_name }}">
                                    </div>
                                </div>
                                <!-- Grid column -->

                                <!-- Grid column -->
                                <div class="col-md-6">
                                    <div class="md-form form-sm mb-0">
                                        <label for="last_name">Last Name</label>
                                        <input type="text" name="last_name" class="form-control form-control-sm"
                                               id="last_name" value="{{ current_user.last_name }}">
                                    </div>
                                </div>
                                <!-- Grid column -->

                            </div>
                            <!-- Grid row -->

                            <!-- Grid row -->
                            <div class="row mb-3">
                                <!-- Grid column -->
                                <div class="col-md-12">
                                    <div class="md-form form-sm mb-0">
                                        <label for="location">Nick Name</label>
                                        <input type="text" name="nick_name" class="form-control form-control-sm"
                                               id="location" value="
                                                {% if current_user.nick_name %}{{ current_user.nick_name }}{% endif %}">
                                    </div>
                                </div>
                                <!-- Grid column -->
                            </div>
                            <!-- Grid row -->

                            <!-- Grid row -->
                            <div class="row mb-3">
                                <!-- Grid column -->
                                <div class="col-md-12">
                                    <div class="md-form form-sm mb-0">
                                        <label for="location">Address</label>
                                        <input type="text" name="location" class="form-control form-control-sm"
                                               id="location" value="
                                                {% if current_user.location %}{{ current_user.location }}{% endif %}">
                                    </div>
                                </div>
                                <!-- Grid column -->
                            </div>
                            <!-- Grid row -->

                            <!-- Grid row -->
                            <div class="row mb-3">
                                <!-- Grid column -->
                                <div class="col-md-12">
                                    <div class="md-form form-sm mb-0">
                                        <label for="website">Website</label>
                                        <input type="text" name="website" class="form-control form-control-sm"
                                               id="website" value="
                                                {% if current_user.website %}{{ current_user.website }}{% endif %}">
                                    </div>
                                </div>
                                <!-- Grid column -->
                            </div>
                            <!-- Grid row -->

                            <!-- Grid row -->
                            <div class="row mb-3">
                                <!-- Grid column -->
                                <div class="col-md-12">
                                    <h4 class="text-muted text-left">About me</h4>
                                    <!-- Basic textarea -->
                                    <div class="md-form mb-0">
                                        <textarea name="bio" class="form-control md-textarea" id="bio"
                                                  placeholder="Basic textarea">{% if current_user.bio %}
                                            {{ current_user.bio }}{% endif %}</textarea>
                                    </div>
                                </div>
                                <!-- Grid column -->
                            </div>
                            <!-- Grid row -->

                            <div class="form-group">
                                <button type="submit" class="btn btn-primary btn-block">Submit</button>
                            </div>
                        </form>
                        <!-- Card content -->
                    </div>
                </div>
                <!-- Card -->

                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-md-4 mb-4">
                    <!-- Card -->
                    <div class="card">
                        <div class="card-body text-center">
                            <h3 class="profile-username">
                                <strong>{{ current_user.email }}</strong>
                            </h3>

                            <p class="text-muted">
                                {% if current_user.roles %} {{ current_user.roles[0].name }} {% endif %}
                            </p>

                            <ul class="list-group list-group-unbordered mb-3">
                                <li class="list-group-item">
                                    <b class="float-left">Username</b>
                                    <a class="float-right">{{ current_user.username }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b class="float-left">Email</b>
                                    <a class="float-right">{{ current_user.email }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b class="float-left">Address</b>
                                    <a class="float-right">{{ current_user.location }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b class="float-left">Website</b>
                                    <a class="float-right">{{ current_user.website }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b class="float-left">Bio</b>
                                    <a class="float-right">{{ current_user.bio }}</a>
                                </li>
                            </ul>

                            <button class="btn btn-danger btn-block btn-sm" data-toggle="modal"
                                    data-target="#modal-default">
                                Change Password
                            </button>
                        </div>

                        <div class="modal fade" id="modal-default">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title">Change Password</h4>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <form method="POST" action="{{ url_for('profile.set_password') }}" role="form"
                                              oninput='password2.setCustomValidity(password.value != password2.value ? "Passwords do not match." : "")'>
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <label for="currentPassword">Old Password</label>
                                                    <input type="password" class="form-control" id="currentPassword"
                                                           required name="old_password">
                                                </div>
                                                <div class="form-group">
                                                    <label for="newPassword">New Password</label>
                                                    <input type="password" class="form-control" id="newPassword"
                                                           required name="password">
                                                </div>
                                                <div class="form-group">
                                                    <label for="confirmedPassword">Confirm Password</label>
                                                    <input type="password" class="form-control" id="confirmedPassword"
                                                           name="password2">
                                                </div>
                                            </div>
                                            <div class="modal-footer justify-content-between">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">
                                                    Close
                                                </button>
                                                <button type="submit" class="btn btn-primary">Save</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Card -->

                <!-- Grid column -->
            </div>
            <!-- Grid row -->

        </section>
        <!-- Section: Team v.1 -->

    </div>
{% endblock %}