template_shop/admin_panel/app/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash

from template_shop.admin_panel.app import db, login_manager
from template_shop.admin_panel.app.forms.auth import LoginForm
from template_shop.infrastructure.database.models import AdminUser

auth_bp = Blueprint("auth_bp", __name__, template_folder="templates", static_folder="static")


@auth_bp.route("/admin/login", methods=["GET", "POST"])
@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    """
    Log-in page for registered users.
    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """

    if current_user.is_authenticated:
        return redirect("/")

    login_user_form = LoginForm()
    if login_user_form.validate_on_submit():
        email = login_user_form.email.data
        password = login_user_form.password.data

        user = db.session.query(AdminUser).filter_by(email=email).first()
        redirect_url = "/"

        if (not user) or (not check_password_hash(user.password, password)):
            flash("Please check your login details and try again.")
            return redirect(request.url)

        login_user(user)
        next_page = request.args.get("next")
        if next_page:
            return redirect(next_page)
        else:
            return redirect(redirect_url)

    return render_template(
        "login.html",
        login_user_form=login_user_form,
    )


@auth_bp.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "POST":
        existing_user = db.session.query(AdminUser).filter_by(email=request.form.get("email")).first()
        if existing_user is None:
            user = AdminUser(email=request.form.get("email"))
            user.set_password(request.form.get("password"))
            db.session.add(user)
            db.session.commit()  # Create new user
            login_user(user)  # Log in as newly created user
            return redirect("/")
        flash("This email is already used")
    if current_user.is_authenticated:
        return redirect(url_for("dashboard_bp.home"))

    return render_template(
        "signup.html",
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""

    if user_id is not None:
        try:
            user = db.session.query(AdminUser).get(user_id)
        except:
            user = None
        return user
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash("Log in to view this page")
    return redirect(url_for("auth_bp.login"))


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth_bp.login"))

template_shop/admin_panel/app/templates/login.html
{% extends "mdb_base.html" %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='adminlte/dist/css/signin.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='adminlte/dist/css/progress.css') }}">
{% endblock styles %}

{% block body_attribs %}security-page{% endblock body_attribs %}

{% block content %}
    {% from "macro.html" import render_field_with_errors %}
    <div class="security-box">
        <div class="card">
            <div class="card-body">
                <div class="text-center primary-text">
                    <h4 style="font-size: 1.2rem"><i class="fas fa-user"></i> {{ _("Login") }}</h4>
                    <hr class="mt-2 mb-2">
                </div>
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="alert alert-danger">
                            {{ messages[0] }}
                        </div>
                    {% endif %}
                {% endwith %}
                <form class="form-signin" method="POST" action="


                        {{ url_for('auth_bp.login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}"
                      name="login_user_form">
                    {{ login_user_form.hidden_tag() }}
                    {{ render_field_with_errors(login_user_form.email, "fas fa-envelope") }}
                    {{ render_field_with_errors(login_user_form.password, "fas fa-lock") }}
                    <div class="text-center mt-2">
                        {{ login_user_form.submit(class_="btn btn-primary btn-block") }}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

template_shop/admin_panel/app/templates/macro.html
{% macro nav_active_item(endpoints, text, icon_class) -%}
    <li class="nav-item ml-3{% if request.endpoint and request.endpoint in endpoints %} active{% endif %}">
        <a class="nav-link waves-effect waves-light font-weight-bold" href="{{ url_for(endpoints[0], **kwargs) }}">
            <i class="{{ icon_class }}"></i>
            {{ text }}
            {% if request.endpoint and request.endpoint == endpoint %}
                <span class="sr-only">(current)</span>
            {% endif %}
        </a>
    </li>
{%- endmacro %}


{% macro render_field_with_errors(field, icon_class=None) %}
    <div class="form-group">
        <div class="input-group">
            {% if icon_class %}
                <div class="input-group-prepend">
                    <span class="input-group-text"><i class="{{ icon_class }}"></i></span>
                </div>
            {% endif %}
            {{ field(placeholder=field.label.text, class_='form-control', **kwargs)|safe }}
        </div>

        {% if field.errors %}
            <ul>
                {% for error in field.errors %}
                    <li>
                        <small class="form-text text-muted mb-4">{{ error }}</small>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endmacro %}

template_shop/admin_panel/app/templates/mdb_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {%- block head %}
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        {%- block metas %}
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <meta http-equiv="x-ua-compatible" content="ie=edge">
        {%- endblock metas %}

        {%- block styles %}
            <!-- Font Awesome -->
            <link rel="stylesheet" type="text/css"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
            <!-- Bootstrap -->
            <link rel="stylesheet" type="text/css"
                  href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" rel="stylesheet">
            <!-- MDB -->
            <link rel="stylesheet" type="text/css"
                  href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
        {%- endblock styles %}

    {%- endblock head %}
</head>

<body class="{% block body_attribs %}{% endblock body_attribs %}">
{% block body %}
    {% block header %}
        {% block sidebar %}
        {% endblock sidebar %}

        {% block navbar %}
        {% endblock navbar %}
    {% endblock header %}

    {% block content %}
    {% endblock content %}

    {% block footer %}
    {% endblock footer %}
{% endblock body %}

{% block scripts %}
{% endblock scripts %}

</body>
</html>

template_shop/admin_panel/app/templates/pagination.html
{% macro simple_pager(pagination,
                      fragment='',
                      prev=('<span aria-hidden="true">&larr;</span> Pre')|safe,
                      next=('Next <span aria-hidden="true">&rarr;</span>')|safe,
                      align='') %}
    <nav aria-label="Page navigation">
        <ul class="pagination {% if align == 'center' %}justify-content-center{% elif align == 'right' %}justify-content-end{% endif %}">
            <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
                <a class="page-link"
                   href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#' }}">
                    {{ prev }}
                </a>
            </li>
            <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
                <a class="page-link"
                   href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#' }}">
                    {{ next }}
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}

{% macro _arg_url_for(endpoint, base) %}
    {# calls url_for() with a given endpoint and **base as the parameters,
    additionally passing on all keyword_arguments (may overwrite existing ones)
    #}
    {%- with kargs = base.copy() -%}
        {%- do kargs.update(kwargs) -%}
        {{ url_for(endpoint, **kargs) }}
    {%- endwith %}
{%- endmacro %}

{% macro render_pagination(pagination,
                           endpoint=None,
                           prev=('&laquo;')|safe,
                           next=('&raquo;')|safe,
                           size=None,
                           ellipses='…',
                           args={},
                           fragment='',
                           align=''
                           )-%}
    {% if fragment != '' and not fragment.startswith('#') %}{% set fragment = '#' + fragment %}{% endif %}
    {% with url_args = {} %}
        {%- do url_args.update(request.view_args if not endpoint else {}),
       url_args.update(request.args if not endpoint else {}),
       url_args.update(args) -%}
        {% with endpoint = endpoint or request.endpoint %}
            <nav aria-label="Page navigation">
                <ul class="pagination {% if size %} pagination-{{ size }}{% endif %} {% if align == 'center' %}justify-content-center{% elif align == 'right' %}justify-content-end{% endif %}"{{ kwargs|xmlattr }}>
                    {# prev and next are only show if a symbol has been passed. #}
                    {% if prev != None -%}
                        <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
                            <a class="page-link" href="


                                    {{ _arg_url_for(endpoint, url_args, page=pagination.prev_num) if pagination.has_prev else '#' }}{{ fragment }}">{{ prev }}</a>
                        </li>
                    {%- endif -%}

                    {%- for page in pagination.iter_pages() %}
                        {% if page %}
                            {% if page != pagination.page %}
                                <li class="page-item">
                                    <a class="page-link" href="


                                            {{ _arg_url_for(endpoint, url_args, page=page) }}{{ fragment }}">{{ page }}</a>
                                </li>
                            {% else %}
                                <li class="page-item active">
                                    <a class="page-link" href="#">{{ page }} <span class="sr-only">(current)</span></a>
                                </li>
                            {% endif %}
                        {% elif ellipses != None %}
                            <li class="page-item disabled"><a class="page-link" href="#">{{ ellipses }}</a></li>
                        {% endif %}
                    {%- endfor %}

                    {% if next != None -%}
                        <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
                            <a class="page-link" href="


                                    {{ _arg_url_for(endpoint, url_args, page=pagination.next_num) if pagination.has_next else '#' }}{{ fragment }}">{{ next }}</a>
                        </li>
                    {%- endif -%}
                </ul>
            </nav>
        {% endwith %}
    {% endwith %}
{% endmacro %}

template_shop/admin_panel/app/templates/signup.html
{% extends "mdb_base.html" %}

{% block content %}
    <div class="container-fluid vh-100">
        <div class="">
            <div class="rounded d-flex justify-content-center">
                <div class="col-md-4 col-sm-12 shadow-lg p-5 bg-light">
                    <div class="text-center">
                        <h3>Sign Up</h3>
                    </div>
                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            <div class="alert alert-danger">
                                {{ messages[0] }}
                            </div>
                        {% endif %}
                    {% endwith %}
                    <form method="POST" action="{{ url_for('auth_bp.signup') }}">
                        <div class="p-4">
                            <div class="input-group mb-3">
                                <input type="email" name="email" class="form-control" placeholder="Email">
                            </div>
                            <div class="input-group mb-3">
                                <input type="password" name="password" class="form-control" placeholder="Password">
                            </div>
                            <button class="btn btn-primary text-center mt-2 btn-block"
                                    style="background-color: #123c69;" type="submit">
                                Register
                            </button>
                            <p class="text-center mt-5">Already have an account?
                                <span class="text-primary"><a href='{{ url_for('auth_bp.login') }}'
                                                              style="color: #123c69;">Sign In</a></span>
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}